### PR TITLE
fix neutral colors not being removed from elements

### LINKED ISSUE #527: Color Neutral doesn't get removed when a new color is selected
I have a heading that I changed to be the neutral color. Then I changed to use a different palette position. I now have 2 color classes because neutral didn't get removed. This happens on other elements as well, like borders
color-neutral-heading

### PR DESCRIPTION
**Pull request by jamesros161**
ISSUE: Resolves #527 

PROJECT: [#14](https://github.com/orgs/BoldGrid/projects/14/views/11)

# Color Neutral doesn't get removed when a new color is selected #

## Test Files ##

[post-and-page-builder-1.25.1-issue-527.zip](https://github.com/BoldGrid/post-and-page-builder/files/12938153/post-and-page-builder-1.25.1-issue-527.zip)

## Testing Instructions ##

1. Install the test zip files linked above.
2. Change the font color of an element to the neutral theme color ( last color in the palette )
3. Change the font color of that same element to some other theme color ( 1, 2, 3, etc )
4. Inspect the element and ensure that the 'color-neutral-color' class was removed from the element and the color of the text accurately reflects the chosen palette color.
5. Repeat steps 2 - 4 but instead of font color, change the outline color, and the border color.

### CODE REVIEW

File: assets/js/builder/controls/color.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ import { Palette } from './color/palette';
 
 		transparentColors: [ 'rgba(0, 0, 0, 0)', 'transparent' ],
 
-		colorClasses: [ 'color1-color', 'color2-color', 'color3-color', 'color4-color', 'color5-color' ],
+		colorClasses: [ 'color1-color', 'color2-color', 'color3-color', 'color4-color', 'color5-color', 'color-neutral-color' ],
```
Comment (avonville) [inline assets/js/builder/controls/color.js:24]: Any reason this is on a single line when the others are separated? Not a big deal, I am assuming is just based on the amount of values in the array.

**Review by avonville — APPROVED** [review]
