### PR TITLE
fix mobile hover boxes

### LINKED ISSUE #448: Hover Boxes - Show Hover Background on mobile devices
image

When I have Show Hover Background selected, the Standard Background is still showing on my phone. 

If Hover Background is selected for mobile, also show any content selected to show on hover:
image

### PR DESCRIPTION
**Pull request by jamesros161**
resolves #448 

# Testing Instructions #

1. Install the test zip attached or use the [one-click-install link](https://www.boldgrid.com/central/cloud-wordpress/try?plugins=https://github.com/BoldGrid/post-and-page-builder/files/9576806/post-and-page-builder-1.21.2.zip).

[post-and-page-builder-1.21.2.zip](https://github.com/BoldGrid/post-and-page-builder/files/9576806/post-and-page-builder-1.21.2.zip)

2. Create a post where one or more columns have a standard background image and a different hover image.
3. Set the hover image to 'Show hover background on mobile'
4. Add a child element to the column, and set the hover effects to 'Show on Hover'
5. Save the post, and view it on a mobile device ( phone or tablet )
6. Ensure that the hover image is shown for the column, and not the standard image on a mobile device.
7. Ensure that the child element within that column is shown at all times on a mobile device

### CODE REVIEW

File: assets/js/public.js [hunk 1]
```diff
@@ -411,8 +411,8 @@ class Public {
 			}
 			css += '}';
 
-			css  += '@media (hover: none) {';
-			css += `.${hoverBoxClass} { background-image: url('${hoverBgUrl}') !important; } }`;
+			css  += '@media screen and (max-width: 991px) {';
```
Comment (avonville) [inline assets/js/public.js:414]: Spacing with the parenthesis?

**Review by avonville — APPROVED** [review]

File: assets/js/public.js (hunk 1 above)
Comment (jamesros161) [reply assets/js/public.js:414]: Per [wordpress coding specification examples](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/css/#media-queries) examples, spacing is not needed

**Comment by nicolepaschen** [comment]
permalink for custom headers & footers 404s
why404

**Comment by nicolepaschen** [comment]
image

the first notice says I don't have PPB active but the 2nd notices knows I actually DO have it installed
