### PR TITLE
Temporary fix for WP 5.5 wpColorPickerL10n issue. Fixes #140

### LINKED ISSUE #140: WP 5.5 - Cannot add blocks, DropTab and popovers missing
Happens when using:
WP 5.5 Beta 3
PPB 1.13.1

Uncaught (in promise) ReferenceError: wpColorPickerL10n is not defined
    _create https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    jQuery 7
    _setupColorPicker https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    init https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    value https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    jQuery 7
    init https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    init https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    load_draggable https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/dist/editor.min.js?ver=1.13.1:1
    Editor https://demo2.cloudwp.dev/trial-2xy40427/wp-content/plugins/post-and-page-builder/assets/js/editor/editor.min.js?ver=1.13.1&wp-mce-49100-20200624:1
    fire https://demo2.cloudwp.dev/trial-2xy40427/wp-includes/js/tinymce/tinymce.min.js?ver=49100-20200624:2
    fire https://demo2.cloudwp.dev/trial-2xy40427/wp-includes/js/tinymce/tinymce.min.js?ver=49100-20200624:2
    yw https://demo2.cloudwp.dev/trial-2xy40427/wp-includes/js/tinymce/tinymce.min.js?ver=49100-20200624:2
    bw https://demo2.cloudwp.dev/trial-2xy40427/wp-includes/js/tinymce/tinymce.min.js?ver=49100-20200624:2
    loadAll https://demo2.cloudwp.dev/trial-2xy40427/wp-includes/js/tinymce/tinymce.min.js?ver=49100-20200624:2

### PR DESCRIPTION
**Pull request by bwmarkle**
@rramo012 I'm not sure how you want to go about addressing #140, but I took a stab at it. Let me know what you think.

### CODE REVIEW

File: includes/class-boldgrid-editor-assets.php [hunk 1]
```diff
@@ -429,6 +433,32 @@ public function enqueue_drag_scripts() {
...
+		 * This is only needed in WordPress >= 5.5 because wpColorPickerL10n has been removed.
+		 * @see https://github.com/WordPress/WordPress/commit/7e7b70cd1ae5772229abb769d0823411112c748b
+		 *
+		 * This is only needed until the wp-color-picker-alpha repo has been updated.
+		 * @see https://github.com/kallookoo/wp-color-picker-alpha/issues/35
+		 *
+		 * The preg_replace is needed to change 5.5-beta3-48571 to 5.5-3-48571 so that the version_compare
+		 * will work properly during the beta phase.
+		 */
+		if ( version_compare( preg_replace( "/[^0-9.-]/", "", $wp_version ), '5.5', '>=' ) ) {
```
Comment (rramo012) [inline includes/class-boldgrid-editor-assets.php:448]: Could we do any version greater than 5.4.99

Comment (bwmarkle) [reply includes/class-boldgrid-editor-assets.php]: Tested, looks like it works. Resolved via https://github.com/BoldGrid/post-and-page-builder/pull/141/commits/ad6c2a859c5c4de587da219f32089e986cd53e53
